version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - cache_data:/app/cache
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_HOST=http://ollama:11434
      - CACHE_EXPIRY=604800
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - S3_STORAGE_BUCKET=

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - cache_data:/app/cache
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_HOST=http://ollama:11434 # Must be accessible by the worker
      - CACHE_DIR=/app/cache
      - CACHE_EXPIRY=604800
      - S3_STORAGE_BUCKET=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
  cache_data: {}
