services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - cache_data:/app/cache
    depends_on:
      - redis
    env_file:
      - .env      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_EXPIRY=604800

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - cache_data:/app/cache
    depends_on:
      - redis
    env_file:
      - .env      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DIR=/app/cache
      - CACHE_EXPIRY=604800

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
  cache_data: {}
