services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - cache_data:/app/cache
    depends_on:
      - redis
    env_file:
      - .env      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_EXPIRY=604800

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - cache_data:/app/cache
    depends_on:
      - redis
    env_file:
      - .env      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DIR=/app/cache
      - CACHE_EXPIRY=604800
      # Hugging Face environment variables
      - HF_HOME=/app/.cache/huggingface
      - TRANSFORMERS_CACHE=/app/.cache/huggingface/transformers
      - HF_DATASETS_CACHE=/app/.cache/huggingface/datasets
    # GPU support - requires nvidia-docker or Docker with GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
  cache_data: {}
